name: Docker Image CI

on: 
  workflow_dispatch:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag structure-nst-cuda-8.0-cudnn5-devel-ubuntu14.04:builder
      
    - name: Test image processing
      run: docker run -t structure-nst-cuda-8.0-cudnn5-devel-ubuntu14.04:builder /test-processing.sh
